name: Itemhunt
version: '1.0.0'
main: love.chihuyu.Itemhunt
authors: [ Hirosuke ]
depend: [CommandAPI]
permissions:
  treasurehunt.*:
    default: op
    children:
      startitemhunt: true
  treasurehunt.startitemhunt:
    default: op